version: "3.9"

services:
  birthday-mysql:
    image: mysql:8.0.33
    container_name: birthday-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: birthday
      MYSQL_USER: birthday
      MYSQL_PASSWORD: birthday
    ports:
      - "3306:3306"
    volumes:
      - mysql8data:/var/lib/mysql

volumes:
  mysql8data:
